### ISSUE TITLE
Does vmtouch support IBM GPFS (Spectrum scale filesystem)

### ISSUE THREAD

**Issue by Amjadhpc** [hoytech/vmtouch#102]
Hello

Just wanted to check if vmtouch has been tested on GPFS

**Comment by hoytech** [comment]
Hi! I have never tested it on this, but that doesn't necessarily mean it won't work. It really depends on how "normal" the filesystem is from a userspace perspective. vmtouch needs `mincore(2)` and some of the madvise/posix_fadvise system calls to work properly.

Best way is to test it yourself and let us know!

**Comment by Amjadhpc** [comment]
Thanks, after testing , creating a vmtouch daemon , does look like GPFS is not supported by vmtouch . For any one needing more technical stuff why its not supported , i asked the same question to  GPFS mailing list  and the response  is here.

https://www.mail-archive.com/gpfsug-discuss@gpfsug.org/msg01165.html
