### ISSUE TITLE
Use standard BSD license

### ISSUE THREAD

**Issue by ryandesign** [hoytech/vmtouch#104]
Would you consider changing your license to the standard [3-clause BSD license](https://opensource.org/license/bsd-3-clause/)?

The license in vmtouch.c and LICENSE differs from the standard 3-clause BSD license in that you include the phrase "All rights reserved" which is not part of that license and is [unnecessary](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence) and that the third clause refers to "The name of the author" rather than "the name of the copyright holder" and "the names of its contributors".

**Comment by hoytech** [comment]
Should be better now, let me know if not. Thanks!

**Comment by ryandesign** [comment]
Thanks. It looks like there's another copy of the license in debian/copyright that needs the same adjustments.
