### ISSUE TITLE
Do I need to re-load files into memory via vmtouch if file size changes

### ISSUE THREAD

**Issue by huangye177** [hoytech/vmtouch#12]
Hi hoytech, 

Thanks a lot for this really cool tool! 

I am working on loading database files into memory via vmtouch. I am wandering that, after I load some database files into memory via vmtouch (e.g., vmtouch -ld /database_path/database_table_files), such as the MySQL index files (.MYI), since these database files will increase through time (although they are the same files), do I need to clean the files out from memory (via vmtouch -ev ) and re-load them into memory through time?

Thanks a lot!

Ye

**Comment by maci0** [comment]
maybe vmtouch can use inotify and re-lock whenever the file content changes.
not sure about the performance implications here tho.

**Comment by hoytech** [comment]
@maci0 - yes that's a really good idea. I think it would also need to monitor the directory containing the file in case the file is unlinked and replaced with a new file.

I think the performance should be reasonable but you should be able to opt out (in?) just in case.

This is one of the features I'm considering for a "libvmtouch" although I haven't had a chance to work on that for a while... One of these days. :)

**Comment by maci0** [comment]
@hoytech inotify has a delete_self event.just need to watch for that and then reopen the file in case a new one was created.
moved_to and moved_from only works within the same directory it seems
there are the inotify-tools to test it out.

**Comment by hoytech** [comment]
I haven't looked into the inotify interface closely before, thanks for the info. I'd guess another thing needed would be to recursively monitor a directory for new/deleted files so we can immediately lock/unlock as needed.

At spotify they re-spawn the vmtouch process periodically. See slide 32 here:

http://www.slideshare.net/JimmyMrdell/playlists-at-spotify-cassandra-summit-london-2013

But of course your suggestion of an inotify solution would be ideal.

**Comment by maci0** [comment]
@hoytech 
also i just found the following in the mlock manpage

```
MCL_FUTURE

Lock all pages which will become mapped into the address space of the process in the future. These could be for instance new pages required by a growing heap and stack as well as new memory mapped files or shared memory regions. 
```

wouldnt this work?

**Comment by maci0** [comment]
ok.. one would still need to monitor file changes and then mmap again it seems

**Comment by hoytech** [comment]
MCL_FUTURE is a very interesting flag to mlockall() although as you noted it might not help vmtouch that much. You're right we'd still have to monitor directories for new/deleted files and monitor for files growing/shrinking and create/adjust our mmaps as appropriate. However, the mlockall(MCL_FUTURE) would let us avoid calling mlock() after calling mmap().

There are some downsides with mlockall() though. One downside is that it locks pages that you probably aren't interested in locking (such as libc and other libraries). Another is that if you hit your rlimit or system-limit on wired memory, I believe you'll get weird EAGAIN failures from mmap() or brk() or whatever which makes it complicated to report this issue to the user. When mlock() fails it's easy to report this problem with the correct error message.

For a real-time app I think MCL_FUTURE would be valuable but I think it's best if vmtouch uses mlock() as the default.

**Comment by hoytech** [comment]
Closing this ticket. In summary, the answer is yes. Currently you need to kill and re-run vmtouch if new files are added or a file's size changes.

Here is a quick and dirty solution from spotify (slide 32):

http://www.slideshare.net/JimmyMrdell/playlists-at-spotify-cassandra-summit-london-2013#slide32

I've added a ticket to consider inotify suggestions made in this thread: #39 

Thanks!

**Comment by Michael-IDA** [comment]
Spotify has some odd formatting on their code (well at least to me).  Here's a re-format into something hopefully easier to read and modify for home use:

```
#!/bin/bash
while true; do
  vmtouch -m 10000000000 -l *head*
  sleep 10m
  kill %vmtouch
done
```
This way it also doesn't just disappear if that slide show goes poof.
