### ISSUE TITLE
vmtouch load file into memory even without any arguments.

### ISSUE THREAD

**Issue by slashbeast** [hoytech/vmtouch#2]
Hi.

Looks like vmtouch always load into memory whatever it tests. I did some tests on few big files, running 'vmtouch /path/to/foo.mkv' took about 4s and after that printed that the file is 100% in memory, it wasnt. After droping cache via /proc/sys/vm/drop_caches again the vmtouch took 4s and according to `free` the file was just prefetched into memory. I did the test on two boxes, one running ext4, dmcrypt and lvm (many layers) and another running just reiserfs.

**Comment by slashbeast** [comment]
Hey,

Seems like the issue is no more. I've tested older commits and still, it does work like it should so it had to be something about all the systems I've tried it on. 

fwiw its no longer an issue with kernel 4.1.0-rc5, glibc 2-21 and gcc 4.9.2.

**Comment by hoytech** [comment]
Thanks for letting me know. Cheers.
