### ISSUE TITLE
request: Read file list from STDIN

### ISSUE THREAD

**Issue by battlesnake** [hoytech/vmtouch#23]
...so I can pipe the file list easily from `find`.  I could use `vmtouch <args> $(find ...)` but may hit the command line length limit.

**Comment by battlesnake** [comment]
Implemented in pull request #24

**Comment by hoytech** [comment]
Great idea, thanks! I'll take a look at your pull request ASAP.

I noticed your preloader repo too: nice :)

**Comment by hoytech** [comment]
We've finally landed a similar patch here: https://github.com/hoytech/vmtouch/pull/49

Also I added -0 and stdin support.

**Comment by battlesnake** [comment]
Good to hear, I got more RAM and an SSD so lost the need for preloader/vmtouch hence why I never finished the patch.
