### ISSUE TITLE
block devices as the parameter

### ISSUE THREAD

**Issue by maq123** [hoytech/vmtouch#30]
Hi,

AFAIK while doing the block device reads (e.g. with dd), the reads will also land in the page cache.
I think that would be useful to be able to observe the stats for that kind of devices as well.

Are there any technical obstacles which are making implementing such feature in the vmtouch?

**Comment by hoytech** [comment]
Great question!

This should be possible... The main hurdle is figuring out the size of the block device which I believe has to be done through an ioctl(BLKGETSIZE64) instead of stat()... This would be linux specific of course.

I'm working on a branch for this feature right now and I'll update this thread when it's ready.

**Comment by hoytech** [comment]
OK I think I have it working, if you like you can checkout this branch and give it a try:

https://github.com/hoytech/vmtouch/tree/support-block-devices

<pre>
doug@pluto:~/vmtouch$ sudo ./vmtouch -v /dev/sda6 
/dev/sda6
[o                            o                              ] 145557/70337536

           Files: 1
     Directories: 0
  Resident Pages: 145557/70337536  568M/268G  0.207%
         Elapsed: 1.5005 seconds
</pre>

**Comment by hoytech** [comment]
Also I believe this data is cached in the buffers cache, which is accounted for in `/proc/meminfo`'s "Buffers" line, not the "Cached" line like normal files are.

**Comment by maq123** [comment]
Just briefly tested it on my machine. Seems to be working quite ok!
Not sure if it is a bug or a feature but touching pages into the memory takes quite long I'd say.
Small example for 512MB dev:
```
root@minsk:/tmp/support-block-devices# time ./vmtouch -t /dev/sda1 
           Files: 1
     Directories: 0
   Touched Pages: 131072 (512M)
         Elapsed: 68.47 seconds

real    1m8.474s
user    0m0.004s
sys     0m5.928s

```

**Comment by hoytech** [comment]
Sorry I've been busy... I'm going to try to figure out why it's slow, maybe something to do with readahead settings or something?

**Comment by hoytech** [comment]
I haven't had a chance to debug the slowness issue, but I've just merged this branch into master for an upcoming release. I'm closing this ticket but I have opened a new one about the slowness: #38

Thanks again for the idea!
