### ISSUE TITLE
Updating atimes

### ISSUE THREAD

**Issue by Ancient123** [hoytech/vmtouch#32]
Would it be possible to touch the file(s) in such a was to not update the atime of the file(s).

I am using vmtouch to load files into memory on reboot on a directory that I normally clear out based on file atime (it is a reverse proxy cache for LAN Party steam downloads)

**Comment by Ancient123** [comment]
Created a pull request with a non-optional open change 
#33

**Comment by hoytech** [comment]
Good idea -- I pretty much always mount everything with noatime.

I'm going to merge your PR I just need to do some ifdef conditionals so it doesn't break non-linux systems.

Thanks!

**Comment by hoytech** [comment]
I've merged your change for the upcoming release. I also added another patch that should hopefully make it so it still works on systems without O_NOATIME support:

a757ea9028abe2cb5b4ac2f5052799a627ccd56e

Thanks again!

**Comment by rs-mrichmond** [comment]
Awesome!
