### ISSUE TITLE
vmtouch not allocating more than 1G

### ISSUE THREAD

**Issue by vikaskedia** [hoytech/vmtouch#35]
I have a folder which has 1.8G of files.

When I give the command:
vmtouch -l /foldername

It shows on screen:
Files: 82502
Directories: 14358
Resident Pages: 337502/416978  1G/1G  80.9%
Elapsed: 1.7909 seconds

I referenced https://github.com/hoytech/vmtouch/issues/18 and changed ulimits to 2G even after that vmtouch does not allocate more then 1G

> ulimit -l 2000000000
> ulimit -l
2000000000

Here is the output of the free command:
> free -h
             total       used       free     shared    buffers     cached
Mem:          125G        60G        65G       289M       1.4G        27G
-/+ buffers/cache:        31G        94G
Swap:         3.7G         0B       3.7G

This is a ubuntu 15.10 system.

Why?

**Comment by hoytech** [comment]
Hmm that's strange. the `-l` switch is supposed to print something like this:

<pre>
# vmtouch -l .
LOCKED 317 pages (1M)
</pre>

(or an error message). Can you please paste your entire terminal session?

In your case since you have such a large number of files you may also need to increase the number of open files rlimit (ulimit -n). I have another branch where it closes the files after mmap()+mlock()ing them, but that is not merged yet (should be in 1.0.3).

**Comment by rahul-chhabra** [comment]
hi @hoytech 
I am facing the same issue as [https://github.com/hoytech/vmtouch/issues/18] #18.
Any tentative release date for 1.0.3 ?

Thanks.

**Comment by hoytech** [comment]
@rahul-chhabra -- There are a few fixes that will be in 1.0.3:

* The fix where it keeps files open when it doesn't need to, which can bump against your NOFILE rlimit
* Removes the default max file size to map (so you don't need to use -m)

You might still run up against the -l "max locked memory" ulimit if you are a non-privileged process, there's not much vmtouch can do about that.

I've got a few things on my plate, but I'll try to get 1.0.3 out early next week... There are a few branches that need cleaning up, that's been the main thing stopping me, but I'll do it ASAP.

**Comment by hoytech** [comment]
So I decided to skip 1.0.3 and go straight to 1.1.0 which is now available from the releases page and the master branch.

Please file a ticket if any new issues come up.

Thanks for your patience!
