### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by dClauzel** [hoytech/vmtouch#46]
In `README.md`, I can see these informations about licence:

>  It is BSD licensed so you can basically do whatever you want with it.

but also 

> vmtouch is copyright (c) 2009-2016 Doug Hoyte and contributors.

So what is the licence precisely?

**Comment by hoytech** [comment]
Good question. The copyright is accurate: I wrote it and a bunch of people have contributed. We have licensed it under the 3-clause BSD license, which is included at the top of the vmtouch.c file.

Nowadays I prefer the 2-clause BSD license, but I'm not sure I could contact all contributors at this point to change that.

**Comment by Earnestly** [comment]
Could you perhaps provide a `LICENSE` file?  Currently it needs to be extracted awkwardly using `awk '/Copyright/,/THIS SOFTWARE,/' vmtouch.c > LICENSE`.

**Comment by hoytech** [comment]
Done: 43866950c3d55847c6b804e67c3b455fc578ab6b

**Comment by ryandesign** [comment]
Then this can be closed?

**Comment by hoytech** [comment]
Thanks, yes, I'll close.
