### ISSUE TITLE
please add parameter to skip searching subdirs belonging to foreign filesystems

### ISSUE THREAD

**Issue by mailinglists35** [hoytech/vmtouch#50]
so if i  have the structure
/
/tmp
/mnt

with /mnt a different filesystem than /

then exclude /mnt from scanning

**Comment by hoytech** [comment]
Hi, good idea, thanks for the suggestion!

We discussed this as an advantage for changing the crawling method to `ftw(3)` since it has `FTW_MOUNT`, but this was easy enough to implement in the current code:

5b365d1bc4a19a4b479da7504ec5da4420bb17ff

Hope this helps.

**Comment by hoytech** [comment]
The -F flag implementing this feature was released in 1.3.0.
