### ISSUE TITLE
packaged for a bunch of rpm distros

### ISSUE THREAD

**Issue by plinnell** [hoytech/vmtouch#55]
https://software.opensuse.org//download.html?project=utilities&package=vmtouch

We've packaged vmtouch for RHEL. openSUSE and SLES. 

Please add the link to the docs.  Eventually, vmtouch will be in openSUSE for sure in the distro.

**Comment by hoytech** [comment]
Thank you! I've added a link in the "OS packages/ports" section of the homepage: https://hoytech.com/vmtouch/
