### ISSUE TITLE
Allow --pidfile option to specify a PID file path

### ISSUE THREAD

**Issue by johnlinp** [hoytech/vmtouch#60]
Like the way `syslog-ng` provides a `--pidfile` option ([man page](https://linux.die.net/man/8/syslog-ng)), I hope `vmtouch` can provide such option too. Thanks.

**Comment by hoytech** [comment]
Yes it's a good idea, pull requests welcome! Otherwise I may get around to it eventually, I'm a bit busy now.

**Comment by johnlinp** [comment]
Great! I will submit a pull request for it.

**Comment by johnlinp** [comment]
I chose `-P` instead of `--pidfile` since no other option has the form of long option.

**Comment by hoytech** [comment]
Yes `-P` is perfect thanks! I'll rmake a new release with your feature soon!
