### ISSUE TITLE
New release for Buildroot inclusion

### ISSUE THREAD

**Issue by ghost** [hoytech/vmtouch#70]
Hello, I'm adding a [vmtouch package to Buildroot][1]. I needed to pull some post-v1.3.0 commits in, however the maintainers would prefer a new release be made. Could that be done?

[1]: http://lists.busybox.net/pipermail/buildroot/2018-November/235878.html

**Comment by hoytech** [comment]
Hi! I just tagged v1.3.1. To be honest I can't remember what I need to do to push out the next debian release, but I can go back through my notes and figure it out eventually. Let me know if you run into any problems. Thanks!
