### ISSUE TITLE
container use vmtouch mlockall file for linux

### ISSUE THREAD

**Issue by zhuq187** [hoytech/vmtouch#96]
i use a k8s daemonset container contains vmtouch, while a k8s node joined the cluster, daemonset setup and start use  "vmtouch -dl" . The file is on nfs or hostpath, and mount to the pod. But i seen the vmtouch page stuck in 5% and not grow any more. did i use vmtouch and docker contianer wrong ? Please help

2022/01/17 16:13:56 Checking model file: /NAS/models/ENGLM004.binary.enc, check interval: 60
2022/01/17 16:14:56            Files: 1
     Directories: 0
  Resident Pages: 338657/6350920  1G/24G  5.33%
         Elapsed: 0.13681 seconds

2022/01/17 16:14:56 Checking model file: /NAS/models/ENGLM004.binary.enc, check interval: 60
2022/01/17 16:15:56            Files: 1
     Directories: 0
  Resident Pages: 338657/6350920  1G/24G  5.33%
         Elapsed: 0.13725 seconds

**Comment by zhuq187** [comment]
Linux ubuntu@ss-dev-cpu-8c32g-0:/NAS/models$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
k8s version: Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4"

**Comment by zhuq187** [comment]
due to k8s resource limit memory. even though daemonset does not set, but the namespace have set default memory limit range. Revert limit range, vmtouch lock file to memory works.

**Comment by hoytech** [comment]
Thanks for the report, and for posting the resolution!
